[package]
name = "ndjt-xml-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "1.1.1"
quick-xml = "0.31.0"
encoding_rs_io = "0.1.7"
